### PR TITLE
Add logos of summer sponsors

### PR DESCRIPTION
**Pull request by Malwine**
We want to add the logos for our summer sponsors.
I added:
- Wunderlist
- Cognitect
- Soundcloud
- Lambdawerk
- Metosin
- Fututrice

Are there more I need to add? Or any to take out?

### CODE REVIEW

**Comment by Malwine** [comment]
@nicsnet Should I add Babbel? What is the status?

**Comment by socksy** [comment]
While we're at it, could we change ".sponsor-area" to ".supporter-area"? The word "sponsor" is a keyword by some adblockers (including mine), making the whole div "display: none !important".

**Comment by Malwine** [comment]
Sure, @socksy, I would appreciate if you could do that.

**Comment by Malwine** [comment]
@socksy  👍

**Comment by nicsnet** [comment]
@Malwine Please add Babbel, so far they're sponsoring the notebooks with a budget of 1000 Euros.

**Comment by socksy** [comment]
Done. Put them above Cognitect but below Wunderlist.

**Comment by vsmart** [comment]
Looks good! 🎉 Thanks @Malwine and @socksy

**Comment by plexus** [comment]
Thanks @Malwine and @socksy!! I changed "SoundCloud" to "SoundCloud Women-IN-Engineering" sice it's their budget. Also added links to the other sponsor links (yay accessibility).

Can I merge this, aye :+1: , nay :-1: ?

**Comment by Malwine** [comment]
@plexus if all confirmed sponsors are up we can MERGE 💃

**Comment by plexus** [comment]
shipped! :ship: :shipit: :anchor: 

ship

**Pull request merged**
