### PR TITLE
Update and change position for newsletter signup

### PR DESCRIPTION
**Pull request by Malwine**
This PR puts the newsletter sign up to the top and updates some text.
:warning: We have to test if the sign up still works.
:warning: To be merged into PR https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/14
screen shot 2016-02-02 at 20 48 42

### CODE REVIEW

**Comment by plexus** [comment]
I like how it looks! I'm not sure about calling it "newsletter" though unless someone takes charge of writing a regular newsletter

**Comment by Malwine** [comment]
Ok, we can name it however we want. Just wanted to find a name we don't have to translate ;)

**Comment by Malwine** [comment]
On the other hand people like it nowadays not to be spammed by a newsletter but receive information when it is important...

**Comment by plexus** [comment]
Yeah my intention with this list is to just use it to announce new workshops or related events.

**Comment by Malwine** [comment]
Then let's call it **News**? Or News Mailing List?

**Comment by plexus** [comment]
Yeah that sounds good

**Comment by Malwine** [comment]
@plexus 
screen shot 2016-02-03 at 14 49 34

**Comment by plexus** [comment]
:+1:

**Comment by Malwine** [comment]
I will merge both then?

**Comment by plexus** [comment]
Yes, please go ahead. Sorry I'm packing now and leaving in the morning, I'm not going to be doing much for ClojureBridge for a little while.

**Comment by Malwine** [comment]
Ok, will do! All the best for your trip!!

**Pull request merged**
