### PR TITLE
Set up coaches page

### PR DESCRIPTION
**Pull request by Malwine**
[Trello Ticket](https://trello.com/c/7K0pIuoa/10-set-up-a-simple-page-for-coaches)

### CODE REVIEW

**Comment by plexus** [comment]
Should this be merged @Malwine ?

**Comment by Malwine** [comment]
@plexus I f you think it is ok and engaging? then yes. I could add more info later once I have ideas.

**Comment by plexus** [comment]
I think it's good :+1: we can always improve it later

**Comment by Malwine** [comment]
Ok, then I'll merge it. Can you send a gif?

**Comment by plexus** [comment]
taylor_swift_dance

Because tradition matters.

**Comment by Malwine** [comment]
@plexus 😂

**Comment by vsmart** [comment]
I only just saw this! Amazing, thank you so much @Malwine 🌈 🎉 💯 👍 ❤️

**Pull request merged**
