### PR TITLE
Change wording

### PR DESCRIPTION
**Pull request by Malwine**
@martinklepsch and @plexus 
I changed the wording to a request of Martin.
Let's just say what we mean by that.
What do you think?

### CODE REVIEW

**Comment by plexus** [comment]
Can't say I'm a fan.

**Comment by Malwine** [comment]
Ok, it was just an attempt. Feel free to change it or leave the old wording :)

**Comment by plexus** [comment]
To elaborate, I'm fine with taking that phrase out of changing the wording of it's too direct ("please mind your personal hygiene"). Just don't say "be a gentleman". Should coaches hold the door open and pull up the chair of the attendees? Should women coaches also be gentleman? Shall we remind the attendees to "behave like a lady"? 

So yeah fine with mostly anything but not a fan of the gentleman 😁

**Comment by plexus** [comment]
Ugh handful of typos I'm sure you can decipher it :)

**Comment by Malwine** [comment]
You are right. Wording is wrong. Please open new PR.

**Comment by martinklepsch** [comment]
Maybe "Please be on time and make sure you're you don't look as if you've been partying three days straight :)" 

What I disliked with the initial sentence was that it seemed top-down to me as if we're treating coaches like little children that do things wrong over and over again ("yes, unfortunately we have to say this"). Diverting from that kind of tone to something a little more casual/fun would be neat :)

**Comment by plexus** [comment]
Yeah totally with you on that. The "unfortunately we have to say this" shouldn't have been there.

**Comment by Malwine** [comment]
I told @martinklepsch already that we were tired when we did this :-D

**Comment by Malwine** [comment]
Can somebody of you please take care tonight?
Before everybody sees it tomorrow?
@plexus @martinklepsch 
Thanks :bee: :heart:

**Comment by thatbettina** [comment]
Hi @Malwine @plexus @martinklepsch -- not sure if help is still needed but my two cents is that we are trying to create community here ESPECIALLY among the coaches, so I don't think we should leave in things like "brush your teeth"! I mean, that assumes it's not commonly done, and we don't assume that about ANYONE, right? And this is kinda alienating if I'm new to Clojure coaching...

**Comment by Malwine** [comment]
Dear Bettina, I will close this PR again, because it will never be merged.
But the discussion should go on.
Can we decide on just taking it out and just saying something about it?

**Comment by plexus** [comment]
I'll update it before tonight @Malwine

**Comment by Malwine** [comment]
Thank you @plexus :blush:

**Comment by plexus** [comment]
merging for your other changes, will update afterwards

**Comment by plexus** [comment]
@Malwine some last changes: https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/commit/0dd212ebdc640e5daa5ccc5c0040bec08fb94dd5

**Pull request merged**
