### PR TITLE
Add Code of Conduct to coaches' training

### PR DESCRIPTION
**Pull request by daveliepmann**

### CODE REVIEW

**Comment by daveliepmann** [comment]
Hold up— I made a mistake. I should've modified the markdown file, not the HTML!!! Then `deck -b docs/coaches_training.deck.md`. My bad. Fixing.

**Comment by daveliepmann** [comment]
Fixed: changes are now in markdown, propagated to HTML via command line.

**Review by lislis — APPROVED** [review]

**Comment by lislis** [comment]
dope

**Comment by vsmart** [comment]
seal

thanks @daveliepmann !

**Pull request merged**
