### PR TITLE
Small edits to coaches training

### PR DESCRIPTION
**Pull request by vsmart**
* 'dumb' is ableist language
* 'understandable' sexism -- not into that phrase. I think 'culturally-influenced' already says it all. 

* I think regenerating this also brought in some changes from @socksy's PR -- #85

### CODE REVIEW

**Comment by JohannaCarola** [comment]
Sounds good! Reading out 'understandable' sexism was very weird... I was surprised to see that on the slides (although I did read them beforehand).

**Comment by daveliepmann** [comment]
- 👍  to adding the "followed by people playing with graphical programming in Quil" to curriculum overview
 - The ground rule we should use is "There are no bad questions" rather than removing the word "dumb". If we want to remove ableist language, the proposed change is lossy: "Questions are always welcome" is a vague platitude outside the context of "even if the student doesn't think their question is valuable". I think we should rewrite the entire line so it clearly communicates our stance to both coaches and learners. "There are no bad questions" is that stance.
 - I think the "what's your current favorite restaurant" icebreaker question is weak and didn't work well. It doesn't reveal anything meaningful about the person to the group, and it's not very powerful as a creator of shared interests or bonds. It's essentially a weirdly constrained version of the perfectly fine and clearly superior "favorite place" question, which we should use instead. (The original "what's your favorite place *in Berlin*" always worked great because *even Berlin newcomers have an answer*, because "I don't know; I'm new to Berlin" (like I answered last year) is a great answer that provides insight into the person's situation and something for folks to bond over.)
 - I agree that "understandable" sexism is a weird phrasing. My solution is to consider not calling coaches sexist at all. What goal of ours does that phrasing advance? To me, our goal is to communicate that we (orga-team) create ClojureBridge workshops to be safe spaces, so it's a *requirement* that coaches agree to that project. That means coaches must keep the space free of sexual advances, sexist/racist/etc jokes, gender generalizations, body comments, and slurs. Let's say that directly: "Make ClojureBridge a safe space for learners". This is more clear than passively pleading coaches "*Try* to..." followed by assigning ownership of that not-cool behavior to the people who showed up to help out.
 - We should move the "ways not to be sexist" slide from the previous bullet point to follow the first Code of Conduct slide. It's a continuation of the same topic and would flow better.
 - I took a lot of notes last night that I'll make into my own PR, but maybe while we're here we can rephrase "Don't use slurs" to something that English as a Foreign Language folks don't need translated. "Discriminatory terms" is the best I have, but it sounds a bit like corporate-HR-speak.

**Comment by vsmart** [comment]
@daveliepmann thanks for the feedback! 

Agreed on all points, and updated slides accordingly, with the exception of: 

> - We should move the "ways not to be sexist" slide from the previous bullet point to follow the first Code of Conduct slide. It's a continuation of the same topic and would flow better.

The first CoC slide mentions that the coc applies to the coaches training, and is part of the "welcome & important info for tonight" stuff, which needs to be right at the start. 
After the welcome, we do introduction rounds. 
Only then do we move on to the first section of the training, which is "what is clojurebridge" and "what does it mean to be a good coach", which is where I think this section belongs.

**Comment by daveliepmann** [comment]
@franka 👍  Awesome. Thanks for this solid PR.

**Pull request merged**
