### PR TITLE
Add logos

### PR DESCRIPTION
**Pull request by plexus**
Add the logos for all the sponsors.

2016-01-11-221434_984x450_scrot

### CODE REVIEW

**Comment by plexus** [comment]
@Malwine or @lislis you want to review and merge?

**Comment by lislis** [comment]
@plexus I only did a quick check, but the sponsors do not appear in Firefox. In Chrome everything looks fine. Does it work in both browsers for you?

**Comment by plexus** [comment]
I developed it on Firefox, and I can see it working on chromium as well. It's pretty basic HTML/CSS... are you sure you're looking at the right version? Maybe it's a browser caching issue?

**Comment by Malwine** [comment]
@plexus I'll have a look now :)

**Comment by Malwine** [comment]
@plexus  Maybe on mobile we want some spacing right below the logo.
See here:
screen shot 2016-01-12 at 10 14 34

@lislis I cannot see the logos with adBlock. When I disable AdBlock for this sit I see them.
Do you have ideas to fix this? Maybe GitHub/jekyll thinks this is an add because of the links?

**Comment by Malwine** [comment]
@plexus maybe we can say **Host 2015 & 2016** Wunderlist and change the heading for the host? Instead of adding them as a sponsor?

**Comment by Malwine** [comment]
Do we also need to add the logos to http://www.clojurebridge.org/events/2016-01-22-berlin ?

**Comment by plexus** [comment]
>  I cannot see the logos with adBlock. When I disable AdBlock for this sit I see them.
> Do you have ideas to fix this? Maybe GitHub/jekyll thinks this is an add because of the links?
> 
> maybe we can say Host 2015 & 2016 Wunderlist and change the heading for the host? Instead of adding them as a sponsor?

Can we merge this already and fix those in a separate PR? It's getting really late, bitcrowd is already asking where their logo is so they can tweet about it.

> Do we also need to add the logos to http://www.clojurebridge.org/events/2016-01-22-berlin ?

Yes, that's the next thing on my todo list.

**Comment by Malwine** [comment]
Yeah ok, I merge it then.

**Comment by Malwine** [comment]
@plexus What about the spacing? Could be relevant for the sponsors to not stick to the others ;)

**Pull request merged**
