### PR TITLE
Add november workshop

### PR DESCRIPTION
**Pull request by Malwine**
TODO
- [x] add numbers of attendees for last workshop
- [ ] rethink displaying all the pictures

### CODE REVIEW

**Comment by Realtin** [comment]
what do you think about adding a link to the blog posts about the workshops? 
we have this one about the 2nd edition: http://foundation.travis-ci.org/2016/01/28/clojurebridge/
and this one about the 4th: https://dalzony.github.io/2016/12/clojure-bridge-berlin

**Comment by vsmart** [comment]
thanks for starting this! :tada: 
how about: listing all past workshops, only showing 1 photo (probably the most recent one)

**Comment by Malwine** [comment]
@vsmart I would even change that to only show the description and picture of the recent workshop and show all other workshops on a second page.

**Comment by Malwine** [comment]
@daveliepmann You have to add a gif when merging 😅

**Comment by daveliepmann** [comment]
@Malwine I forgot!

**Pull request merged**
