### PR TITLE
Update sponsors for November 2016

### PR DESCRIPTION
**Pull request by vsmart**
Updates sponsor logos for the next workshop

@plexus Could you send me a logo for LambdaIsland, then I can add you. 

adresses https://github.com/clojurebridge-berlin/organization/issues/128

### CODE REVIEW

**Comment by vsmart** [comment]
@plexus This is ready to be merged

**Comment by plexus** [comment]
martin

**Comment by martinklepsch** [comment]
😂

**Comment by Malwine** [comment]
Omg! A classic!! 

Thank you @vsmart 💯👌🎉

**Comment by Malwine** [comment]
Btw, I think it would be cool to display all logos of the previous sponsors on the sponsor-us page if they aren't there already. Might be 2 or 3.

**Pull request merged**
